name: 'send deployment event to Datadog DORA Metrics'
description: 'send deployment event to Datadog Dora Metrics https://docs.datadoghq.com/dora_metrics/'
inputs:
  datadog-service-name:
    description: 'service name in datadog'
  datadog-env:
    description: 'env name in datadog'
  datadog-api-key:
    description: 'DataDog API Acckess Key'
  started-at:
    description: 'start datetime of deploy'
    required: true
  finished-at:
    description: 'finished datetime of deploy. default is now time'
  git-repository-url:
    description: 'url of target repository. default is current repository'
  git-commit-sha:
    description: 'git commit sha of deployment. default is GITHUB_SHA'

runs:
  using: 'node20'
  main: 'src/index.js'
