name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  docker-image-tag:
    # @see https://hub.docker.com/r/datadog/ci/tags
    description: 'image tag of datadog/ci'
    default: 'latest'
  service-name:
    description: 'service name in datadog'
    required: true
  datadog-env:
    description: 'env in datadog'
  started-at:
    description: 'start datetime of deploy'
    required: true
  finished-at:
    description: 'finished datetime of deploy'
  git-repository-url:
    description: 'url of target repository'
  git-commit-sha:
    description: ''

env:
  git-repository-url: "${{ format('{0}/{1}', github.server_url, github.repository) }}"
  git-commit-sha: "${{ github.sha }}"

runs:
  using: 'docker'
  image: "docker://datadog/ci:latest"
  env:
    DD_BETA_COMMANDS_ENABLED: 1
  args:
    - dora
    - deployment
    - --service
    - ${{ inputs.service-name }}
    - --env
    - ${{ inputs.datadog-env }}
    - --started-at
    - ${{ inputs.started-at }}
    - --finished-at
    - ${{ inputs.finished-at }}
    - --git-repository-url
    - ${{ env.git-repository-url }}
    - --git-commit-sha
    - ${{ env.git-commit-sha }}
