name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  docker-image-tag:
    # @see https://hub.docker.com/r/datadog/ci/tags
    description: 'image tag of datadog/ci'
    default: 'latest'
  service-name:
    description: 'service name in datadog'
    required: true
  datadog-env:
    description: 'env in datadog'
  started-at:
    description: 'start datetime of deploy'
    required: true
  finished-at:
    description: 'finished datetime of deploy'
  git-repository-url:
    description: 'url of target repository'
  git-commit-sha:
    description: ''

runs:
  using: 'docker'
  image: "Dockerfile"
  env:
    STARTED_AT: ${{ inputs.started-at }}
    FINISHED_AT: ${{ inputs.finished-at }}
    DD_SERVICE: ${{ inputs.service-name }}
    DD_ENV: ${{ inputs.datadog-env }}
