on:
  push:
    branches:
      - master
      - develop

jobs:
  delivery:
    runs-on: ubuntu-latest
    name: ci
    steps:
      - id: deploy-start
        name: record deploy start time
        run: echo unix-time="$(date +%s)" >> "${GITHUB_OUTPUT}"

      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      - run: sleep 3

      - uses: ./ # Uses an action in the root directory
        with:
          datadog-service-name: eiel/datadog-dora-metrics-deployments-action
          datadog-api-key: ${{ secrets.DD_API_KEY }}
          datadog-env: ${{ github.ref_name }}
          started-at: ${{ steps.deploy-start.outputs.unix-time }}
