on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: record deploy start time
        run: echo deploy-started-at="$(date +%s)" >> "${GITHUB_ENV}"

      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./ # Uses an action in the root directory
        with:
          docker-image-tag: latest
          service-name: eiel/datadog-dora-metrics-deployments-action
          datadog-env: ${{ env.GITHUB_REF }}
          started-at: ${{ env.deploy-started-at }}
          finished-at: "$(date +%s)"
          git-repository-url: "${{ format('{0}/{1}', env.GITHUB_SERVER_URL, env.GITHUB_REPOSITORY) }}"
          git-commit-sha: "${{ env.GITHUB_SHA }}"
