on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: ci
    steps:
      - name: record deploy start time
        run: echo deploy-started-at="$(date +%s)" >> "${GITHUB_ENV}"

      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      - run: sleep 3

      - name: record deploy start time
        run: echo deploy-finished-at="$(date +%s)" >> "${GITHUB_ENV}"

      - uses: ./ # Uses an action in the root directory
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
        with:
          docker-image-tag: latest
          service-name: eiel/datadog-dora-metrics-deployments-action
          datadog-env: ${{ github.ref_name }}
          started-at: ${{ env.deploy-started-at }}
          finished-at: "${{ env.deploy-finished-at }}"
          # git-repository-url: "${{ format('{0}/{1}', github.server_url, github.repository) }}"
          # git-commit-sha: "${{ github.sha }}"
